# Use a Red Hat UBI minimal image as the base image
FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

# Install the necessary packages for building and running COBOL programs
RUN microdnf install -y gnucobol libmicrohttpd

RUN ln -s /usr/lib64/libmicrohttpd.so.12.46.0  /usr/lib64/libmicrohttpd.so

COPY microhttpd.cbl /app/microhttpd.cbl

WORKDIR /app

RUN cobc -v -free -static -x microhttpd.cbl -o microhttpd -lmicrohttpd && \
    chown 1001:0 microhttpd && \
    chmod g+rx microhttpd

USER 1001

CMD ["./microhttpd"]

EXPOSE 8080